//@version=5
indicator(title="Bar Counter",overlay=true)//, , overlay=false)timeframe="", timeframe_gaps=true)
// support, resistance, chart pattern, gann, fib, pivot point, avg price, vwap, sar, mom, price, volume

isToday(i) =>
    a = ta.change(time("D"),i) ? 1 : 0
    a
noOfBars() =>
	int counter = 0
	for i = 1 to 78
        if isToday(i)
		    counter := counter + 1
            // there are 78 5 min candles in a day
	counter := 78 - counter 

print(string txt) =>
    var table t = table.new(position.middle_right, 1, 1)
    table.cell(t, 0, 0, txt, bgcolor = color.yellow)


print(str.tostring(noOfBars()))


