// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Amlanpatra16

//@version=5
indicator("test ICMC BO Strict LIVE func alert",overlay=true,max_bars_back=100)
rcnt_bars = input.int(title="Recent Bars",defval=80,minval=1)
show_breakout_label = input.bool(true, "Show Breakout Label")



resistance_ic = high
support_ic = low
start_idx = 0

ic(idx) =>
    res = (math.abs(open[idx] - close[idx])) <= (high[idx] - low[idx])/2 ? 1 : 0
    res

isToday(i) =>
    a = ta.change(time("D"),i) ? 1 : 0
    a
noOfBars() =>
	int counter = 0
	for i = 1 to 78
        if isToday(i)
		    counter := counter + 1
            // there are 78 5 min candles in a day
	counter := 78 - counter 


print(string txt) =>
    var table t = table.new(position.middle_right, 1, 1)
    table.cell(t, 0, 0, txt,text_color=color.white, bgcolor = color.black)
del_lines() =>
    a_allLines = line.all
    if array.size(a_allLines) > 0
        for i = 0 to array.size(a_allLines) - 1
            line.delete(array.get(a_allLines, i))
del_last2lines() =>
    a_allLines = line.all
    if array.size(a_allLines) >= 2
        // for i = 0 to array.size(a_allLines) - 1
        line.delete(array.pop(a_allLines))
        line.delete(array.pop(a_allLines))


find_nextIC(idx) =>
    result = 0
    for i = idx to 1
        if(ic(i))
            result := i
            break
    result




breakout_screener() =>
    bars = noOfBars()
    is_mom_and_outside_range = 0 
    recent_bars = 0
    if(rcnt_bars > bars)
        recent_bars := bars
    recent_bars := find_nextIC(recent_bars)
    resistance_ic = high[recent_bars]
    support_ic = low[recent_bars]
    start_idx = recent_bars

    final_breakout = 0
    for i = recent_bars to 0
    // for i = recent_bars to 0
        if (ic(i))
            is_mom_and_outside_range := 0
            if(high[i] >= resistance_ic)
                resistance_ic := high[i]
            if(low[i] <= support_ic)
                support_ic := low[i]
            final_breakout := 0
        else if (not (ic(i)))
            if ((close[i] <= resistance_ic) and (close[i] >= support_ic))   // mc but not breakout
                final_breakout := 0
                // continue
            else  // mc breakout candle
                if ((final_breakout == 1) or is_mom_and_outside_range == 1)
                    final_breakout := 0
                else
                    final_breakout := 1
                    is_mom_and_outside_range := 1
                if(find_nextIC(i) == 0)
                    continue
                else
                    start_idx := find_nextIC(i)
                    resistance_ic := high[start_idx]
                    support_ic := low[start_idx]

    final_breakout  // return 1 if breakout, 0 if no breakout







final_val = breakout_screener()
if show_breakout_label// and (final_str != "")
    print(final_val == 1 ? "breakout" : "")
else
    na

last_message = 'BO ' + str.tostring(syminfo.tickerid)
last_message := string(last_message)
alertcondition(final_val == 1, title= "ICMC BO" , message='Breakout')
