//@version=5
// This indicator is made of CCI 34 of 5min and CCI 34 of 30mins
indicator(title="Nimblr CCI",timeframe_gaps=true)//, format=format.price, precision=2, timeframe="", timeframe_gaps=true)
// length = input.int(20, minval=1)
length = 34


// src = input(hlc3, title="Source")
src = hlc3


// ma = ta.sma(src, length)
// cci = (src - ma) / (0.015 * ta.dev(src, 34))
// plot(cci, "CCI", color=#2962FF)
// band1 = hline(100, "Upper Band", color=#787B86, linestyle=hline.style_dashed)
// band0 = hline(-100, "Lower Band", color=#787B86, linestyle=hline.style_dashed)
// fill(band1, band0, color=color.rgb(33, 150, 243, 90), title="Background")


// min30sma = ta.sma(src,34)
// min30sma_data = request.security(syminfo.tickerid,"30", min30sma, lookahead=barmerge.lookahead_on)
// min30_hlc3_data = request.security(syminfo.tickerid, "30", src, lookahead=barmerge.lookahead_on)
// min30_cci = (min30_hlc3_data - min30sma_data) / (0.015 * ta.dev(min30_hlc3_data,34))
// plot(min30_cci, "30min CCI", color=color.red)


min5sma = ta.sma(src,34)
min5sma_data = request.security(syminfo.tickerid,"5", min5sma,barmerge.gaps_on)//,lookahead=barmerge.lookahead_on)
min5_hlc3_data = request.security(syminfo.tickerid, "5", src, barmerge.gaps_on)//,lookahead=barmerge.lookahead_on)
min5_cci = (min5_hlc3_data - min5sma_data) / (0.015 * ta.dev(min5_hlc3_data,34))
plot(min5_cci, "5min CCI", color=color.red)
























// //@version=5
// // This indicator is made of CCI 34 of 5min and CCI 34 of 30mins
// indicator(title="Test CCI")//,timeframe_gaps=true)//, format=format.price, precision=2, timeframe="", timeframe_gaps=true)
// // length = input.int(20, minval=1)
// length = 34


// // src = input(hlc3, title="Source")
// src = hlc3


// // ma = ta.sma(src, length)
// // cci = (src - ma) / (0.015 * ta.dev(src, 34))
// // plot(cci, "CCI", color=#2962FF)
// // band1 = hline(100, "Upper Band", color=#787B86, linestyle=hline.style_dashed)
// // band0 = hline(-100, "Lower Band", color=#787B86, linestyle=hline.style_dashed)
// // fill(band1, band0, color=color.rgb(33, 150, 243, 90), title="Background")

// min30_src = request.security(syminfo.tickerid,"30", src,barmerge.gaps_on)
// min30sma = ta.sma(min30_src,length)
// // min30sma_data = request.security(syminfo.tickerid,"30", min30sma)//,barmerge.gaps_on,lookahead=barmerge.lookahead_on)
// // min30_hlc3_data = request.security(syminfo.tickerid, "30", src)//,barmerge.gaps_on,lookahead=barmerge.lookahead_on)
// // min30_cci = (min30_hlc3_data - min30sma_data) / (0.015 * ta.dev(min30_hlc3_data,length))
// min30_cci = (min30_src - min30sma)  / (0.015 * ta.dev(min30_src,length))
// plot(min30_cci, "30min CCI", color=color.red)


// // min5sma = ta.sma(src,34)
// // min5sma_data = request.security(syminfo.tickerid,"5", min5sma,barmerge.gaps_on)//,lookahead=barmerge.lookahead_on)
// // min5_hlc3_data = request.security(syminfo.tickerid, "5", src, barmerge.gaps_on)//,lookahead=barmerge.lookahead_on)
// // min5_cci = (min5_hlc3_data - min5sma_data) / (0.015 * ta.dev(min5_hlc3_data,34))
// // plot(min5_cci, "5min CCI", color=color.red)